// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecipesTestAPI.Models;

namespace RecipesTestAPI.Migrations
{
    [DbContext(typeof(RecipesTestAPIContext))]
    [Migration("20181121054511_tet")]
    partial class tet
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("RecipesTestAPI.Models.RecipesItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Ingredient");

                    b.Property<string>("Title");

                    b.Property<string>("Uploaded");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.ToTable("RecipesItem");
                });

            modelBuilder.Entity("RecipesTestAPI.Models.TagItem", b =>
                {
                    b.Property<int>("TagID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("RecipesId");

                    b.Property<int?>("RecipesItemId");

                    b.HasKey("TagID");

                    b.HasIndex("RecipesItemId");

                    b.ToTable("TagItem");
                });

            modelBuilder.Entity("RecipesTestAPI.Models.TagItem", b =>
                {
                    b.HasOne("RecipesTestAPI.Models.RecipesItem")
                        .WithMany("Tag")
                        .HasForeignKey("RecipesItemId");
                });
#pragma warning restore 612, 618
        }
    }
}
